label test_end_1:
    a "Kazuki, sit down. I have to tell you a story."
    mc "... I don't understand. We don't have time for this."
    a "Please. This is the only thing we have time for."
    nmc "Last-minute strategizing in the form of a parable? Fine, I suppose that would be a good place to end."
    nmc "But her eyes start to water, and her legs start to shake. Her fingers curl up, and her neck loosens. Is she scared?"
    mc "I'll get you some water."
    nmc "And of course, in response, I say something egg-shit retarded. Where the fuck am I going to get water?"
    nmc "But that doesn't matter, because she grabs my wrist, with a grip that no human could break."
    a "No. I need you... to. To hear this."
    mc "Alright. What is it?"
    a "..."
    nmc "She can't get the words out. But her face tells me what a fool I have been."
    nmc "Yes I've been fighting. Yes I've been winning. But despite how I've felt, that making sure that we've been able to survive this whole time..."
    nmc "I haven't been living. I have been surviving and nothing more."
    nmc "... Just making damned sure that the world was in a sane state."
    a "...I shouldn't exist."
    mc "No, you should exist because I need you to function now."
    a "But that's not how things were. I was a broken shield, but you picked me up off of the ground."
    mc "Well that's because you seemed reliable... and besides, I couldn't just get rid of you if I wanted to."
    nmc "I didn't take her. No. That's not what happened. There was more than that."
    a "No, dammit! You took care of me, and let me see the Earth and you held me. You told me everything would be all right."
    mc "And now look! The world is a better place, good! That's all we set out to do, right? Save the world from some crazed teenager!"
    nmc "I'm lying through my teeth. We shared the same trench and the same school. I cared about her, but not in a way that mattered."
    mc "We've been doing a job and we're going to finish it."
    a "You can't..."
    mc "And why not?"
    nmc "She collapses in my arms, one more time. Curling her body into an oval, she let's herself go."
    nmc "And one more time, the seconds move slower. And this time, nothing could have prepared me for what she said."
    a "I love you!"
    nmc "She's whispering, scared of what she herself is saying next, knowing how horrific it is."
    a "You taught me how to love, even though you never loved anyone. You taught me how to fight, even though I never did any fighting."
    a "And you taught me how to forgive, even though you never held a grudge."
    nmc "She lifts her head up and kisses me. Slowly. Her lips cover my lips, and she looks down on me."
    a "You need time to learn the same things. I have to finish what we started."
    nmc "She picks up the Aegis, and starts to head down the stairs."
    nmc "... I can't watch her shake anymore. For my sake, she's going to face Rin's monsters."
    nmc "Because I did my job and nothing more, she's going to force me to live, just a while longer."
    nmc "It's my turn to grab her arm."
    mc "That's suicide."
    a "Do you remember what you taught me about suicide?"
    nmc "... I remember."
    a "You said it's from a Latin very that means to kill oneself. Rin may kill me, but I will certainly kill her."
    nmc "Now she's the one lying. She thinks she has me nearly figured out. And after two years of seeing me work, I don't blame her."
    nmc "But there's one detail that she missed."
    mc "Not alone."
    nmc "I grab her other hand, and stare her in the eyes."
    mc "I see now. It took me two years, but I see."
    mc "Not alone. Not again."
    nmc "And for the first time in two years, I am the one that kisses her. And for the first time in two years, I surprise all seven feet of her."
    #... load the fight scene, which is somewhat pre-programmed.
    nmc "... Scientists all over have been in this position."
    nmc "The funding is in place. The employees have been hired. The formulae check-out. The samples have been procured."
    nmc "Everything goes far too right."
    nmc "Rin stares at me with eyes that will never blink again."
    nmc "And I am a dying man."
    a "... We did it."
    nmc "Athena coughs up another batch of blood, and reaches out with her left hand to stroke my right cheek."
    nmc "Her right arm is gone."
    nmc "And both of my legs are gone."
    mc "But we're not going to make it."
    a "And that's okay now."
    nmc "Her hand went limp, and I felt my own body give out."
    nmc "It was nice knowing you, Athena..."
    return
    