init python:
    scopes = {}
    special_cases = ["combat_test"]
    base_scope={'ingame':"Kazuki",
        'main_name':"?",
        'main_type':"kk",
        'main_char':Combatant("Kazuki", 5, 11, 11, 20, 14, 14, 20, 100, 50, 100, 
                              100, None, 0, None, 0, None, 0, None, 0, "Fists", 
                              "Nothing", ["Pound", "Check"], "Human", False,
                              100, 0, 65, 75),
        'showMCStatus':True,
        'answers':[],
        'flags':[],
        'points':init_points(),
        'reminders':[],
        'j_name':"Jonathan",
        'theweekday':3,
        'themonth':9,
        'theday':21,
        'theyear':2010,
        'dayofyear':264,
        'yearlim':365,
        'daylim':30,
        'stringweekday':"Tuesday",
        'stringmonth':"September",
        'main_char_cash':200.00,
        'has_phone':False,
        'corruption':0,
        'walletshow':True,
        'ui_check':False,
        'strchange':"",
        'progress':"000",
        'shadow_name':"Shadow",
        's':DynamicCharacter("shadow_name", color="#808080", kind=char_black),
        'nvls':DynamicCharacter("shadow_name", color="#808080", kind=nvl_black),
        'mtname':"Math Teacher",
        'mt':DynamicCharacter("mtname"),
        'dname':"\"Father\"",
        'd':DynamicCharacter("dname"),
        'r':Character('Rin', color="#000000", kind=char_null),
        'nvlr':Character('Rin', color="#000000", kind=nvl_null),
        'l':Character('Lawrence', color='#F87431', kind=char_orange),
        'nvll':Character('Lawrence', color='#F87431', kind=nvl_orange),
        'j':DynamicCharacter("j_name", color="#ADD8E6", kind=char_blue),
        'nvlj':DynamicCharacter("j_name", color="#ADD8E6", kind=nvl_blue),
        'n':Character('Natalie', color='#FAAFBE', kind=char_pink),
        'nvlnb':Character('Natalie', color='#FAAFBE', kind=nvl_pink),
        't':Character('Tammy', color='#00FF00', kind=char_green),
        'nvlt':Character("Tammy", color='#00FF00', kind=nvl_green),
        'w':Character('Wil', color="#FFFF00", kind=char_yellow),
        'nvlt':Character('Wil', color="#FFFF00", kind=nvl_yellow),
        'b':Character('Ben', color="#6600CC", kind=char_purple),
        'nvlb':Character('Ben', color="#6600CC", kind=nvl_purple),
        'li':Character('Lilian', color="#00CC00", kind=char_forest),
        'nvlli':Character('Lilian', color="#00CC00", kind=nvl_forest),
        'ro':Character('Robert', color="#FF9900", kind=char_tan),
        'nvlro':Character('Robert', color="#FF9900", kind=nvl_tan),
        'a':Character('Athena', color="#FF0000", kind=char_red),
        'nvla':Character('Athena', color="#FF0000", kind=nvl_red),
        'ry':Character('Ryan', color= "#46C6C6", kind=char_teal),
        'nvlry':Character('Ryan', color="#46C6C6", kind=nvl_teal),
        'se':Character('Selena', color= "#CC6699", kind=char_bubgum),
        'nvlse':Character('Selena', color="#CC6699", kind=nvl_bubgum),
        'mc':DynamicCharacter("main_name", color="#C0C0C0", kind=char_gray),
        'nvlmc':DynamicCharacter("main_name", color="#C0C0C0", kind=nvl_gray),
        'nmc':Character(None, what_style="main_gray"),
        'nnvlmc':Character(None, color="#C0C0C0", kind=nvl_gray_narr),
        'minutes':460,
        'clock':True,
        'in_side_note':False}
    #==============
    scopes["Kazuki_1b"]={'main_name':"Kazuki"}
    scopes["Kazuki_1c"]={'main_name':"Kazuki",
        'main_char_currentBelly':70,
        'answers':["law_hesitation", "nat_will_try"],
        'minutes':596,
        'points':[-2, 0, 0, 0, 0, 0, 0, 0]}
        